chore: disable pull request branch restriction workflow for main branch

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -35,13 +35,13 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      - name: Enforce develop to main workflow
-        # When full PL becomes functional; it will be from develop → staging → main.
-        if: github.base_ref == 'main' && github.head_ref != 'develop'
-        run: |
-          echo "❌ Error: Pull requests to 'main' are only allowed from 'develop'."
-          echo "Current source branch: ${{ github.head_ref }}"
-          exit 1
+      # - name: Enforce develop to main workflow
+      #   # When full PL becomes functional; it will be from develop → staging → main.
+      #   if: github.base_ref == 'main' && github.head_ref != 'develop'
+      #   run: |
+      #     echo "❌ Error: Pull requests to 'main' are only allowed from 'develop'."
+      #     echo "Current source branch: ${{ github.head_ref }}"
+      #     exit 1
 
       - name: Setup Bun (or Node)
         uses: oven-sh/setup-bun@v1
